### ISSUE TITLE
False-Negative when testing the notification

### ISSUE THREAD

**Issue by hypervtechnics** [crobibero/Jellyfin.Plugins.Gotify#11]
I entered my credentials, clicked save and then test.

The UI states that an error occured. Although I receive the notification.

An exception is logged:

```text
[2019-11-18 14:09:34.320 +00:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugins.Gotify.Api.ServerApiEndpoints.PostAsync(TestNotification request)
   at Jellyfin.Plugins.Gotify.Api.ServerApiEndpoints.Post(TestNotification request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
Likely you hit save with the other bug, you can either ignore it or manually go to `$JELLYFIN/plugins/configurations/Jellyfin.Plugins.Gotify.xml` and remove the entry with a blank UserId

**Comment by hypervtechnics** [comment]
Oh man... 🤣 I will do this later as I currently have no access to the filesystem... Thanks again, will report later! :)

**Comment by hypervtechnics** [comment]
Okay that worked!
