### ISSUE TITLE
Doesn't seem to work with 10.3.6

### ISSUE THREAD

**Issue by zkvsky** [crobibero/Jellyfin.Plugins.Gotify#3]
I'm getting error while testing connection [ There was an error sending the test notification. Please check your notification settings and try again.]
My serwer ip is http://x.xxxx.xx:5992
and app token is apllied properly

log spits this:
[ERR] Error processing request
System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.SetPostData(System.Collections.Generic.IDictionary`2<System.String,System.String>)'.
   at Jellyfin.Plugins.Gotify.Api.ServerApiEndpoints.PostAsync(TestNotification request)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugins.Gotify.Api.ServerApiEndpoints.PostAsync(TestNotification request)
   at Jellyfin.Plugins.Gotify.Api.ServerApiEndpoints.Post(TestNotification request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by crobibero** [comment]
Need to update the dependencies to fix this issue, #2 is blocking fix
