### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by grahamPegNetwork** [crobibero/Jellyfin.Plugins.Gotify#5]
OS: Debian stable
Jellyfin: 10.3.6 via Docker
Gotify: 2.0.6 via Docker

Hello, I'm attempting to set up gotify notifications in Jellyfin and discovered that the test notification button throws an error. I also tested by triggering a notification and it throws the same error. The error content is as follows:

`System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.SetPostData(System.Collections.Generic.IDictionary`2<System.String,System.String>)'.
   at Jellyfin.Plugins.Gotify.Api.ServerApiEndpoints.PostAsync(TestNotification request)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugins.Gotify.Api.ServerApiEndpoints.PostAsync(TestNotification request)
   at Jellyfin.Plugins.Gotify.Api.ServerApiEndpoints.Post(TestNotification request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
`
I have verified that the gotify server is responding to two other systems (Curl, external web service) and have attempted using multiple forms of the host without success. (localhost, 127...., public url)

Let me know if there is any other information that can help with troubleshooting.

**Comment by crobibero** [comment]
Thanks for the report. Some things were removed with 10.3.6, so I have a PR that is waiting for a fix on the server so the notification can be properly set

**Comment by grahamPegNetwork** [comment]
Hello @crobibero , additional information:
1. First off, I may have messed up. Apparently I need to learn about docker networking; I have both jellyfin and Gotify running as separate instances and it appears they are unable to communicate. (I discovered this when attempting to connect other services...whoops)
2. Assuming the root of the issue is point 1, a bit better error handling may be in order. The frontend message is fine, however the backend (pasted above) tells me the error isn't really being fully handled and is just throwing.

Apologies for the misguided report, time to go set up a docker network!

**Comment by grahamPegNetwork** [comment]
Oh, belated update: I fixed the host issue, however connections still fail, so it does appear that there is an issue.

**Comment by crobibero** [comment]
Still waiting for 10.3.7 to be released before I can make sure the PR works

**Comment by anthonylavado** [comment]
@crobibero Thanks for doing that in #4. We're just looking at one last thing in the 10.3.7 beta, and then we should be good.

**Comment by crobibero** [comment]
Fixed with #4
